#!/usr/bin/env bash
# Property Test: Upload Share Access Control (Property 4)
# Purpose: For each per-user upload share config, verify:
#          read only = yes, valid users = owner only
# Validates: Requirements 36.1, 36.3, 36.4
# Usage: bash tests/test_phase4_property_upload_share_access.sh

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

TESTS_RUN=0
TESTS_PASSED=0
TESTS_FAILED=0

print_pass() { echo -e "${GREEN}✓ PASS${NC}: $1"; TESTS_PASSED=$((TESTS_PASSED + 1)); }
print_fail() { echo -e "${RED}✗ FAIL${NC}: $1"; TESTS_FAILED=$((TESTS_FAILED + 1)); }

# Test against the example template (smb.conf is generated on the server)
SMB_CONF="configs/samba/smb.conf.example"
if [[ ! -f "$SMB_CONF" ]]; then
    echo -e "${RED}✗ FATAL${NC}: smb.conf.example not found"
    exit 1
fi
echo "Using smb.conf: $SMB_CONF"
echo ""

# Also check the task module that generates upload shares
TASK_SCRIPT="scripts/deploy/tasks/task-ph4-06-configure-samba-uploads.sh"
if [[ ! -f "$TASK_SCRIPT" ]]; then
    echo -e "${RED}✗ FATAL${NC}: task-ph4-06-configure-samba-uploads.sh not found"
    exit 1
fi
echo "Using task script: $TASK_SCRIPT"
echo ""

echo "========================================"
echo "Property 4: Upload Share Access Control"
echo "========================================"
echo ""

# --- Check 1: Task script generates 'read only = yes' for upload shares ---
TESTS_RUN=$((TESTS_RUN + 1))
if grep -q 'read only = yes' "$TASK_SCRIPT"; then
    print_pass "Task script sets 'read only = yes' for upload shares"
else
    print_fail "Task script MISSING 'read only = yes' for upload shares"
fi

# --- Check 2: Task script sets 'valid users' to single username (owner only) ---
TESTS_RUN=$((TESTS_RUN + 1))
# The script uses ${username} as valid users — verify it's a single user, not a group (@)
if grep -q 'valid users = ${username}' "$TASK_SCRIPT" || grep -q 'valid users = \${username}' "$TASK_SCRIPT"; then
    print_pass "Task script sets 'valid users' to single owner username"
else
    print_fail "Task script MISSING single-user 'valid users' for upload shares"
fi

# --- Check 3: Task script does NOT use write list for upload shares ---
TESTS_RUN=$((TESTS_RUN + 1))
# Extract only the smb.conf block generated by the heredoc (between EOFSMB markers)
HEREDOC_BLOCK=$(sed -n '/cat.*>>.*SMB_CONF.*<<.*EOFSMB/,/^EOFSMB$/p' "$TASK_SCRIPT" 2>/dev/null || true)
if [[ -n "$HEREDOC_BLOCK" ]]; then
    if echo "$HEREDOC_BLOCK" | grep -q 'write list'; then
        print_fail "Upload share heredoc contains 'write list' (should be read-only only)"
    else
        print_pass "Upload share heredoc does NOT contain 'write list' (read-only enforced)"
    fi
else
    # Fallback: check the whole script for write list near upload share context
    if grep -A5 '\-uploads\]' "$TASK_SCRIPT" | grep -q 'write list'; then
        print_fail "Upload share config contains 'write list' (should be read-only only)"
    else
        print_pass "Upload share config does NOT contain 'write list' (read-only enforced)"
    fi
fi

# --- Check 4: Task script sets 'browseable = yes' ---
TESTS_RUN=$((TESTS_RUN + 1))
if grep -q 'browseable = yes' "$TASK_SCRIPT"; then
    print_pass "Task script sets 'browseable = yes' for upload shares"
else
    print_fail "Task script MISSING 'browseable = yes' for upload shares"
fi

# --- Check 5: Task script does NOT use group syntax (@) for valid users ---
TESTS_RUN=$((TESTS_RUN + 1))
if [[ -n "$HEREDOC_BLOCK" ]]; then
    if echo "$HEREDOC_BLOCK" | grep -q 'valid users = @'; then
        print_fail "Upload share uses group (@) for valid users (should be single user)"
    else
        print_pass "Upload share does NOT use group (@) for valid users"
    fi
else
    if grep -A5 '\-uploads\]' "$TASK_SCRIPT" | grep -q 'valid users = @'; then
        print_fail "Upload share uses group (@) for valid users (should be single user)"
    else
        print_pass "Upload share does NOT use group (@) for valid users"
    fi
fi

# --- Check 6: Share name follows {username}-uploads pattern ---
TESTS_RUN=$((TESTS_RUN + 1))
# The script builds share_name as "${username}-uploads" via variable assignment
if grep -qE 'share_name=.*-uploads' "$TASK_SCRIPT"; then
    print_pass "Share name follows {username}-uploads naming pattern"
else
    print_fail "Share name does NOT follow {username}-uploads pattern"
fi

# --- Check 7: Share path uses Immich upload directory with UUID ---
TESTS_RUN=$((TESTS_RUN + 1))
# The script defines IMMICH_UPLOAD_DIR and builds share_path from it + uuid
if grep -q '/mnt/data/services/immich/upload' "$TASK_SCRIPT"; then
    print_pass "Share path uses /mnt/data/services/immich/upload/{uuid} pattern"
else
    print_fail "Share path MISSING /mnt/data/services/immich/upload/ base path"
fi

# --- Check existing smb.conf.example for Media/Family share patterns ---
# (These are prerequisites — upload shares depend on existing share structure)
echo ""
echo "--- Baseline: Existing share structure ---"

TESTS_RUN=$((TESTS_RUN + 1))
if grep -q '^\[Media\]' "$SMB_CONF"; then
    print_pass "smb.conf.example contains [Media] share"
else
    print_fail "smb.conf.example MISSING [Media] share"
fi

TESTS_RUN=$((TESTS_RUN + 1))
if grep -q '^\[Family\]' "$SMB_CONF"; then
    print_pass "smb.conf.example contains [Family] share"
else
    print_fail "smb.conf.example MISSING [Family] share"
fi

echo ""
echo "========================================"
echo "Upload Share Access Control Summary"
echo "========================================"
echo "Checks run:    $TESTS_RUN"
echo -e "Passed:        ${GREEN}$TESTS_PASSED${NC}"
echo -e "Failures:      ${RED}$TESTS_FAILED${NC}"
echo "$TESTS_PASSED / $TESTS_RUN checks passed"
echo "========================================"

if [[ $TESTS_FAILED -eq 0 ]]; then
    echo -e "${GREEN}✓ Property 4 holds: Upload shares are read-only with single-user access control${NC}"
    exit 0
else
    echo -e "${RED}✗ Property 4 violated: Upload share access control checks failed${NC}"
    exit 1
fi
