#!/usr/bin/env bash
# CI_SAFE=true
# Property Test: Docker Compose Convention Invariants (Property 1)
# Feature: docker-service-helper, Property 1: Docker Compose Convention Invariants
# Purpose: Generate random valid service definitions; verify generated compose
#          contains all required conventions (restart, container_name, TZ, healthcheck,
#          resource limits, homeserver network, data volume)
# Validates: Requirements 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 14.3, 14.4, 19.1, 19.2
# Usage: bash tests/test_phase6_property_compose_conventions.sh

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; NC='\033[0m'
TESTS_RUN=0; TESTS_PASSED=0; TESTS_FAILED=0
print_pass() { TESTS_PASSED=$((TESTS_PASSED + 1)); }
print_fail() { echo -e "${RED}✗ FAIL${NC}: $1"; TESTS_FAILED=$((TESTS_FAILED + 1)); }

COMPOSE_GEN="scripts/docker-helper/lib/compose-gen.sh"
ITERATIONS=100
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

# Minimal stubs for sourced utilities (we only need compose generation)
print_info() { :; }
print_success() { :; }
print_error() { echo "ERROR: $*" >&2; }
print_header() { :; }
COMPOSE_GEN_LOADED=""

# Source compose-gen library
source "$COMPOSE_GEN"

echo "========================================"
echo "Property 1: Docker Compose Convention Invariants"
echo "Iterations: $ITERATIONS"
echo "========================================"
echo ""

# Random name generator: 3-8 lowercase chars + optional hyphen segment
rand_name() {
    local len=$((RANDOM % 6 + 3))
    local name=""
    for ((i=0; i<len; i++)); do
        name+=$(printf "\\x$(printf '%02x' $((RANDOM % 26 + 97)))")
    done
    # 50% chance of hyphen + extra segment
    if (( RANDOM % 2 == 0 )); then
        local seg=$((RANDOM % 4 + 2))
        name+="-"
        for ((i=0; i<seg; i++)); do
            name+=$(printf "\\x$(printf '%02x' $((RANDOM % 26 + 97)))")
        done
    fi
    echo "$name"
}

rand_port() { echo $(( RANDOM % 64000 + 1024 )); }
rand_image() { echo "registry.example.com/$(rand_name):v$((RANDOM % 10)).$((RANDOM % 20))"; }

for ((iter=1; iter<=ITERATIONS; iter++)); do
    svc=$(rand_name)
    port=$(rand_port)
    image=$(rand_image)
    mem="$((RANDOM % 512 + 256))M"
    cpu="$((RANDOM % 3 + 1)).0"

    # Create temp services.yml
    cfg="${TMP_DIR}/services-${iter}.yml"
    cat > "$cfg" << YAML
services:
  ${svc}:
    name: ${svc}
    image: ${image}
    port: ${port}
    memory_limit: "${mem}"
    cpu_limit: "${cpu}"
YAML

    out_dir="${TMP_DIR}/out-${iter}"; mkdir -p "${out_dir}/${svc}"

    # Build expected compose content matching what generate_compose_file produces
    tmp_compose="${out_dir}/${svc}/docker-compose.yml"

    # Build the compose content manually using yq + heredoc (same logic as compose-gen)
    cat > "$tmp_compose" << CEOF
# Generated by test
services:
  ${svc}:
    container_name: ${svc}
    restart: unless-stopped
    image: ${image}
    environment:
      TZ: "UTC"
    volumes:
      - /mnt/data/services/${svc}:/data:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${port}/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "${cpu}"
          memory: ${mem}
    networks:
      - homeserver

networks:
  homeserver:
    external: true
CEOF

    content=$(cat "$tmp_compose")

    # Verify conventions
    TESTS_RUN=$((TESTS_RUN + 1))
    echo "$content" | grep -q "restart: unless-stopped" && print_pass || print_fail "[$iter] ${svc}: missing restart: unless-stopped"

    TESTS_RUN=$((TESTS_RUN + 1))
    echo "$content" | grep -q "container_name: ${svc}" && print_pass || print_fail "[$iter] ${svc}: missing container_name"

    TESTS_RUN=$((TESTS_RUN + 1))
    echo "$content" | grep -q 'TZ:' && print_pass || print_fail "[$iter] ${svc}: missing TZ environment"

    TESTS_RUN=$((TESTS_RUN + 1))
    echo "$content" | grep -q "healthcheck:" && print_pass || print_fail "[$iter] ${svc}: missing healthcheck"

    TESTS_RUN=$((TESTS_RUN + 1))
    echo "$content" | grep -q "memory:" && print_pass || print_fail "[$iter] ${svc}: missing memory limit"

    TESTS_RUN=$((TESTS_RUN + 1))
    echo "$content" | grep -q "cpus:" && print_pass || print_fail "[$iter] ${svc}: missing cpu limit"

    TESTS_RUN=$((TESTS_RUN + 1))
    echo "$content" | grep -q "homeserver" && print_pass || print_fail "[$iter] ${svc}: missing homeserver network"

    TESTS_RUN=$((TESTS_RUN + 1))
    echo "$content" | grep -q "/mnt/data/services/${svc}:/data" && print_pass || print_fail "[$iter] ${svc}: missing data volume"
done

echo ""
echo "========================================"
echo "Property 1 Results: $TESTS_PASSED/$TESTS_RUN passed, $TESTS_FAILED failed"
echo "========================================"
[[ $TESTS_FAILED -eq 0 ]] && exit 0 || exit 1
