#!/bin/bash
# Task: Create Jellyfin Docker Compose configuration
# Phase: 3 (Core Services)
# Number: 10
# Prerequisites:
#   - Phase 2 complete
#   - /mnt/data/services/jellyfin/ created
#   - Configuration loaded (TIMEZONE, INTERNAL_SUBDOMAIN)
# Parameters:
#   --dry-run: Validate without making changes
# Exit Codes:
#   0 = Success
#   1 = Failure
#   3 = Configuration error
# Environment Variables Required:
#   TIMEZONE, INTERNAL_SUBDOMAIN
# Environment Variables Optional:
#   None

set -euo pipefail

# Root check
if [[ $EUID -ne 0 ]]; then
    echo "Error: This script must be run as root (use sudo)" >&2
    exit 1
fi

# Source utilities (absolute paths)
source /opt/homeserver/scripts/operations/utils/output-utils.sh

# Parse parameters
DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

# Validate required environment variables
if [[ -z "${TIMEZONE:-}" ]]; then
    print_error "TIMEZONE environment variable not set"
    exit 3
fi

if [[ -z "${INTERNAL_SUBDOMAIN:-}" ]]; then
    print_error "INTERNAL_SUBDOMAIN environment variable not set"
    exit 3
fi

# Validate prerequisites
print_info "Validating prerequisites..."

# Check /mnt/data/services/jellyfin/ exists
if [[ ! -d /mnt/data/services/jellyfin ]]; then
    print_error "/mnt/data/services/jellyfin/ does not exist (should be created in Task 2.2)"
    exit 3
fi

# Check media group exists and get GID
if ! getent group media &> /dev/null; then
    print_error "media group does not exist (should be created in Phase 2)"
    exit 3
fi

MEDIA_GID=$(getent group media | cut -d: -f3)
print_info "media group GID: $MEDIA_GID"

# Check idempotency
if [[ -f configs/docker-compose/jellyfin.yml ]]; then
    print_info "jellyfin.yml already exists"
    if [[ "$DRY_RUN" == false ]]; then
        read -rp "Overwrite? (y/n): " confirm
        if [[ "$confirm" != "y" ]]; then
            print_info "Skipping Jellyfin Docker Compose creation"
            exit 0
        fi
    fi
fi

# Execute task
if [[ "$DRY_RUN" == true ]]; then
    print_info "[DRY-RUN] Would create configs/docker-compose/jellyfin.yml"
    print_info "[DRY-RUN] Configuration:"
    print_info "  - TIMEZONE: $TIMEZONE"
    print_info "  - INTERNAL_SUBDOMAIN: $INTERNAL_SUBDOMAIN"
    print_info "  - JELLYFIN_PublishedServerUrl: https://media.${INTERNAL_SUBDOMAIN}"
    print_info "  - media group GID: $MEDIA_GID"
else
    print_info "Creating Jellyfin Docker Compose configuration..."
    
    # Create docker-compose directory if it doesn't exist
    mkdir -p configs/docker-compose
    
    # Create jellyfin.yml
    cat > configs/docker-compose/jellyfin.yml << EOFJELLYFIN
# Jellyfin Media Streaming Service
# Generated by Phase 3 deployment script
# DO NOT EDIT MANUALLY - Managed by deployment automation

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"    # HTTP (internal only, proxied via Caddy)
    volumes:
      - /mnt/data/services/jellyfin/config:/config
      - /mnt/data/services/jellyfin/cache:/cache
      - /mnt/data/media:/media:ro
    environment:
      TZ: '${TIMEZONE}'
      JELLYFIN_PublishedServerUrl: 'https://media.${INTERNAL_SUBDOMAIN}'
    group_add:
      - "${MEDIA_GID}"  # media group - allows container to read /mnt/data/media/
    networks:
      - homeserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Optional: Hardware acceleration (Intel Quick Sync)
    # Uncomment if Intel GPU available:
    # devices:
    #   - /dev/dri:/dev/dri

networks:
  homeserver:
    external: true
EOFJELLYFIN
    
    print_success "Created configs/docker-compose/jellyfin.yml"
    
    # Validate docker-compose.yml syntax
    print_info "Validating docker-compose.yml syntax..."
    if docker compose -f configs/docker-compose/jellyfin.yml config &> /dev/null; then
        print_success "docker-compose.yml syntax valid"
    else
        print_error "docker-compose.yml syntax invalid"
        exit 1
    fi
    
    print_info "Review and customize jellyfin.yml as needed"
    print_info "To enable hardware acceleration, uncomment the devices section"
fi

print_success "Task complete"
exit 0
