#!/bin/bash
# Task: Deploy Immich Docker Compose stack
# Phase: 4 (Photo Management)
# Number: 02
# Combines: Generate immich.yml (Task 3.2) + Deploy stack (Task 3.3)
# Prerequisites:
#   - Phase 2 complete (Docker, homeserver network)
#   - Immich directories created (Task 3.1)
#   - services.env and secrets.env configured with Immich variables
# Parameters:
#   --dry-run: Validate without making changes
# Exit Codes:
#   0 = Success
#   1 = Failure
#   3 = Configuration error
# Environment Variables Required (services.env):
#   IMMICH_VERSION, UPLOAD_LOCATION, DB_DATA_LOCATION, DB_USERNAME,
#   DB_DATABASE_NAME, MEDIA_GROUP_GID, TIMEZONE
# Environment Variables Required (secrets.env):
#   DB_PASSWORD

set -euo pipefail

# Root check
if [[ $EUID -ne 0 ]]; then
    echo "Error: This script must be run as root (use sudo)" >&2
    exit 1
fi

# Source utilities (absolute paths)
source /opt/homeserver/scripts/operations/utils/output-utils.sh

# Parse parameters
DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

# Configuration paths
FOUNDATION_ENV="/opt/homeserver/configs/foundation.env"
SERVICES_ENV="/opt/homeserver/configs/services.env"
SECRETS_ENV="/opt/homeserver/configs/secrets.env"
COMPOSE_FILE="configs/docker-compose/immich.yml"

# Docker compose command with all env files
COMPOSE_CMD="docker compose --env-file $FOUNDATION_ENV --env-file $SERVICES_ENV --env-file $SECRETS_ENV -f $COMPOSE_FILE"

# Source environment files (only if vars not already exported by orchestrator)
if [[ -z "${IMMICH_VERSION:-}" ]]; then
    print_info "Loading configuration..."
    if [[ -f "$FOUNDATION_ENV" ]]; then
        source "$FOUNDATION_ENV"
    fi
    if [[ ! -f "$SERVICES_ENV" ]]; then
        print_error "services.env not found at $SERVICES_ENV"
        exit 3
    fi
    source "$SERVICES_ENV"
    if [[ -f "$SECRETS_ENV" ]]; then
        set +u
        source "$SECRETS_ENV"
        set -u
    fi
else
    print_info "Using exported configuration from orchestrator..."
fi

# Validate required env vars from services.env
REQUIRED_VARS=(IMMICH_VERSION UPLOAD_LOCATION DB_DATA_LOCATION DB_USERNAME DB_DATABASE_NAME MEDIA_GROUP_GID TIMEZONE)
for var in "${REQUIRED_VARS[@]}"; do
    if [[ -z "${!var:-}" ]]; then
        print_error "$var not set in services.env"
        exit 3
    fi
done

# Validate required secrets
if [[ -z "${DB_PASSWORD:-}" ]]; then
    print_error "DB_PASSWORD not set in secrets.env"
    exit 3
fi

# Validate prerequisites
print_info "Validating prerequisites..."

if ! docker info &> /dev/null; then
    print_error "Docker is not running"
    exit 3
fi

if ! docker network inspect homeserver &> /dev/null; then
    print_error "Docker network 'homeserver' does not exist (should be created in Phase 2)"
    exit 3
fi

# Look up media group GID from system
if ! getent group media &> /dev/null; then
    print_error "media group does not exist (should be created in Phase 2)"
    exit 3
fi
MEDIA_GID=$(getent group media | cut -d: -f3)
print_info "media group GID: $MEDIA_GID"

# ============================================================
# Part 1: Generate immich.yml (Task 3.2)
# ============================================================
print_header "Part 1: Generate Immich Docker Compose Configuration"

# Check idempotency
GENERATE_COMPOSE=false
if [[ -f "$COMPOSE_FILE" ]]; then
    print_info "immich.yml already exists"
    if [[ "$DRY_RUN" == false ]]; then
        read -p "Overwrite? (y/n): " confirm
        if [[ "$confirm" == "y" ]]; then
            GENERATE_COMPOSE=true
        else
            print_info "Skipping immich.yml generation, proceeding to deployment..."
        fi
    else
        GENERATE_COMPOSE=true
    fi
else
    GENERATE_COMPOSE=true
fi

if [[ "$DRY_RUN" == true ]]; then
    print_info "[DRY-RUN] Would generate $COMPOSE_FILE"
    print_info "[DRY-RUN] Configuration:"
    print_info "  - IMMICH_VERSION: $IMMICH_VERSION"
    print_info "  - UPLOAD_LOCATION: $UPLOAD_LOCATION"
    print_info "  - DB_DATA_LOCATION: $DB_DATA_LOCATION"
    print_info "  - DB_USERNAME: $DB_USERNAME"
    print_info "  - DB_DATABASE_NAME: $DB_DATABASE_NAME"
    print_info "  - MEDIA_GROUP_GID: $MEDIA_GID (from system)"
    print_info "  - TIMEZONE: $TIMEZONE"
elif [[ "$GENERATE_COMPOSE" == true ]]; then
    print_info "Generating $COMPOSE_FILE..."
    mkdir -p configs/docker-compose

    # Write compose file with quoted heredoc — all ${VAR} written literally
    cat > "$COMPOSE_FILE" << 'EOFIMMICH'
# Immich Photo Management Docker Compose (Phase 4)
# Generated by task-ph4-02-deploy-immich-stack.sh
# DO NOT EDIT MANUALLY - Managed by deployment automation
# Requires: foundation.env (TIMEZONE)
# Requires: services.env (IMMICH_VERSION, UPLOAD_LOCATION, DB_DATA_LOCATION, MEDIA_GROUP_GID, DB_USERNAME, DB_DATABASE_NAME)
# Requires: secrets.env (DB_PASSWORD)

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    container_name: immich-server
    restart: unless-stopped
    ports:
      - "2283:2283"
    volumes:
      - ${UPLOAD_LOCATION}:/data:rw
      - /mnt/data/media/Photos:/mnt/media/Photos:ro
      - /mnt/data/family/Photos:/mnt/family/Photos:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_HOSTNAME: immich-postgres
      REDIS_HOSTNAME: immich-redis
      TZ: ${TIMEZONE}
    group_add:
      - "${MEDIA_GROUP_GID}"
    depends_on:
      immich-postgres:
        condition: service_healthy
      immich-redis:
        condition: service_healthy
    networks:
      - homeserver
    healthcheck:
      test: ["CMD", "immich-healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  immich-ml:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    container_name: immich-ml
    restart: unless-stopped
    volumes:
      - model-cache:/cache:rw
    environment:
      TZ: ${TIMEZONE}
    networks:
      - homeserver
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:3003/ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 4G
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"

  immich-redis:
    image: docker.io/valkey/valkey:9
    container_name: immich-redis
    restart: unless-stopped
    networks:
      - homeserver
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  immich-postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich-postgres
    restart: unless-stopped
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      TZ: ${TIMEZONE}
    shm_size: 128mb
    networks:
      - homeserver
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"

volumes:
  model-cache:

networks:
  homeserver:
    external: true
EOFIMMICH

    # Replace MEDIA_GROUP_GID placeholder with actual numeric GID from system
    sed -i "s/\${MEDIA_GROUP_GID}/${MEDIA_GID}/g" "$COMPOSE_FILE"

    print_success "Generated $COMPOSE_FILE"
    print_info "MEDIA_GROUP_GID resolved to: $MEDIA_GID"

    # Validate docker compose syntax
    print_info "Validating Docker Compose syntax..."
    if $COMPOSE_CMD config &> /dev/null; then
        print_success "Docker Compose syntax valid"
    else
        print_error "Docker Compose syntax invalid"
        $COMPOSE_CMD config 2>&1 | head -20
        exit 1
    fi
fi

# ============================================================
# Part 2: Deploy Immich stack (Task 3.3)
# ============================================================
print_header "Part 2: Deploy Immich Docker Compose Stack"

if [[ ! -f "$COMPOSE_FILE" ]]; then
    print_error "$COMPOSE_FILE does not exist (Part 1 must complete first)"
    exit 3
fi

# Immich containers to check
IMMICH_CONTAINERS=(immich-server immich-ml immich-redis immich-postgres)

if [[ "$DRY_RUN" == true ]]; then
    print_info "[DRY-RUN] Would deploy Immich stack"
    print_info "[DRY-RUN] Would run: $COMPOSE_CMD up -d"
    print_info "[DRY-RUN] Would wait for containers to reach healthy status (max 120s)"
    print_info "[DRY-RUN] Containers: ${IMMICH_CONTAINERS[*]}"
else
    print_info "Deploying Immich stack..."
    $COMPOSE_CMD up -d

    # Wait for all containers to reach healthy status (max 120 seconds)
    print_info "Waiting for containers to reach healthy status (max 120s)..."
    TIMEOUT=120
    ELAPSED=0
    INTERVAL=5

    while [[ $ELAPSED -lt $TIMEOUT ]]; do
        ALL_HEALTHY=true
        for container in "${IMMICH_CONTAINERS[@]}"; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' "$container" 2>/dev/null || echo "missing")
            if [[ "$STATUS" != "healthy" ]]; then
                ALL_HEALTHY=false
                break
            fi
        done

        if [[ "$ALL_HEALTHY" == true ]]; then
            print_success "All Immich containers are healthy"
            break
        fi

        sleep "$INTERVAL"
        ELAPSED=$((ELAPSED + INTERVAL))
        print_info "Waiting... ${ELAPSED}s / ${TIMEOUT}s"
    done

    if [[ "$ALL_HEALTHY" != true ]]; then
        print_error "Not all containers reached healthy status within ${TIMEOUT}s"
        print_info "Current container status:"
        for container in "${IMMICH_CONTAINERS[@]}"; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' "$container" 2>/dev/null || echo "not found")
            echo "  $container: $STATUS"
        done
        print_error "Check logs: docker logs <container-name>"
        exit 1
    fi

    # Verify all containers running
    print_info "Verifying all Immich containers are running..."
    for container in "${IMMICH_CONTAINERS[@]}"; do
        if ! docker ps --format '{{.Names}}' | grep -q "^${container}$"; then
            print_error "Container $container is not running"
            exit 1
        fi
    done

    # Display container status table
    print_info "Immich container status:"
    docker ps --filter "name=immich" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

    print_success "Immich stack deployed successfully"
    print_info "Access Immich at: http://192.168.1.2:2283 (internal)"
    print_info "After configuring Caddy and DNS, access at: https://photos.home.mydomain.com"
fi

print_success "Task complete"
exit 0
