#!/bin/bash
# Task: Create Samba configuration files
# Phase: 3 (Core Services)
# Number: 03
# Prerequisites:
#   - Phase 2 complete
#   - Configuration loaded (SAMBA_WORKGROUP, SAMBA_SERVER_STRING)
# Parameters:
#   --dry-run: Validate without making changes
# Exit Codes:
#   0 = Success
#   1 = Failure
#   3 = Configuration error
# Environment Variables Required:
#   SAMBA_WORKGROUP, SAMBA_SERVER_STRING
# Environment Variables Optional:
#   None

set -euo pipefail

# Root check
if [[ $EUID -ne 0 ]]; then
    echo "Error: This script must be run as root (use sudo)" >&2
    exit 1
fi

# Parse parameters
DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

# Validate required environment variables
if [[ -z "${SAMBA_WORKGROUP:-}" ]]; then
    echo "Error: SAMBA_WORKGROUP environment variable not set" >&2
    exit 3
fi

if [[ -z "${SAMBA_SERVER_STRING:-}" ]]; then
    echo "Error: SAMBA_SERVER_STRING environment variable not set" >&2
    exit 3
fi

# Check idempotency
if [[ -f configs/samba/smb.conf ]]; then
    echo "smb.conf already exists"
    if [[ "$DRY_RUN" == false ]]; then
        read -p "Overwrite? (y/n): " confirm
        if [[ "$confirm" != "y" ]]; then
            echo "Skipping Samba configuration creation"
            exit 0
        fi
    fi
fi

# Execute task
if [[ "$DRY_RUN" == true ]]; then
    echo "[DRY-RUN] Would create configs/samba/ directory"
    echo "[DRY-RUN] Would create configs/samba/smb.conf"
else
    echo "Creating Samba configuration directory..."
    mkdir -p configs/samba
    
    echo "Creating smb.conf..."
    cat > configs/samba/smb.conf << 'EOFSMB'
# Samba Configuration File
# Generated by Phase 3 deployment script
# DO NOT EDIT MANUALLY - Managed by deployment automation

[global]
   # Server identification
   workgroup = WORKGROUP_PLACEHOLDER
   server string = SERVER_STRING_PLACEHOLDER
   
   # Security
   security = user
   map to guest = Bad User
   
   # Protocol versions (SMB1 disabled for security)
   server min protocol = SMB2
   server max protocol = SMB3
   client min protocol = SMB2
   client max protocol = SMB3
   
   # Logging
   log level = 1
   max log size = 50
   
   # Performance tuning
   socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=131072 SO_SNDBUF=131072
   read raw = yes
   write raw = yes
   
   # Recycle bin (global configuration)
   vfs objects = recycle
   recycle:repository = .recycle/%U
   recycle:keeptree = yes
   recycle:versions = yes
   recycle:touch = yes
   recycle:maxsize = 0
   recycle:exclude = *.tmp, *.temp, *.cache
   recycle:exclude_dir = /tmp, /temp, /cache

# Personal shares will be added dynamically by user provisioning scripts
# Example format:
# [username]
#    path = /mnt/data/users/username
#    browseable = yes
#    read only = no
#    valid users = username
#    write list = username
#    create mask = 0700
#    directory mask = 0700
#    vfs objects = recycle
#    recycle:repository = .recycle/%U

# Family shared folder
[Family]
   path = /mnt/data/family
   browseable = yes
   read only = no
   valid users = @family
   write list = @family
   create mask = 0770
   directory mask = 0770
   force group = family
   vfs objects = recycle
   recycle:repository = .recycle/%U

# Media library (curated content)
[Media]
   path = /mnt/data/media
   browseable = yes
   read only = no
   valid users = @family
   write list = @media
   create mask = 0664
   directory mask = 0775
   force group = media
   force create mode = 0664
   force directory mode = 0775
   vfs objects = recycle
   recycle:repository = .recycle/%U
EOFSMB
    
    # Replace placeholders with actual values
    sed -i "s/WORKGROUP_PLACEHOLDER/${SAMBA_WORKGROUP}/g" configs/samba/smb.conf
    sed -i "s/SERVER_STRING_PLACEHOLDER/${SAMBA_SERVER_STRING}/g" configs/samba/smb.conf
    
    echo "✓ Created configs/samba/smb.conf"
    
    # Validate smb.conf syntax (if testparm is available)
    if command -v testparm &> /dev/null; then
        echo "Validating smb.conf syntax..."
        if testparm -s configs/samba/smb.conf &> /dev/null; then
            echo "✓ smb.conf syntax valid"
        else
            echo "✗ smb.conf syntax invalid" >&2
            exit 1
        fi
    else
        echo "testparm not available, skipping syntax validation"
    fi
    
    echo "Review and customize smb.conf as needed"
fi

echo "✓ Task complete"
exit 0
