#!/bin/bash
# shellcheck disable=SC2155
set -euo pipefail

# Library: Docker Compose Generation (compose-gen.sh)
# Generates valid Docker Compose V2 YAML from service definitions in services.yml
# Dependencies: yq, docker compose, output-utils.sh
# Requirements: 2.1–2.14, 14.1–14.6

[[ -n "${COMPOSE_GEN_LOADED:-}" ]] && return 0
readonly COMPOSE_GEN_LOADED=1

# Convention defaults
readonly _CG_MEM="512M" _CG_CPU="1.0" _CG_NET="homeserver"
readonly _CG_HC_INT="30s" _CG_HC_TMO="10s" _CG_HC_RET="3"

# Generate a Docker Compose file from a service definition
# Args: service_name services_config compose_dir data_base timezone [dry_run]
# Output: {compose_dir}/{service_name}/docker-compose.yml
generate_compose_file() {
    local svc_name="$1" cfg="$2" out_dir="$3" data_base="$4" tz="$5" dry_run="${6:-false}"
    local s=".services.${svc_name}"
    local tmp; tmp=$(mktemp /tmp/compose-gen-XXXXXX.yml)
    # shellcheck disable=SC2064
    trap "rm -f '$tmp'" RETURN

    local image=$(yq -r "${s}.image // \"\"" "$cfg")
    local bld_ctx=$(yq -r "${s}.build.context // \"\"" "$cfg")
    local bld_df=$(yq -r "${s}.build.dockerfile // \"Dockerfile\"" "$cfg")
    local port=$(yq -r "${s}.port // \"\"" "$cfg")
    local no_proxy=$(yq -r "${s}.no_proxy // false" "$cfg")
    local mem=$(yq -r "${s}.memory_limit // \"${_CG_MEM}\"" "$cfg")
    local cpu=$(yq -r "${s}.cpu_limit // \"${_CG_CPU}\"" "$cfg")

    # Header
    cat > "$tmp" << EOF
# Generated by docker-service-helper — do not edit manually
# Service: ${svc_name}
# Generated: $(date -Iseconds)
services:
  ${svc_name}:
    container_name: ${svc_name}
    restart: unless-stopped
EOF

    # Image / build
    if [[ -n "$bld_ctx" ]]; then
        printf '    build:\n      context: %s\n      dockerfile: %s\n' "$bld_ctx" "$bld_df" >> "$tmp"
        [[ -n "$image" ]] && echo "    image: ${image}" >> "$tmp"
    else
        echo "    image: ${image}" >> "$tmp"
    fi

    # Ports (only no_proxy services publish to host)
    if [[ "$no_proxy" == "true" ]] && [[ -n "$port" ]]; then
        printf '    ports:\n      - "%s:%s"\n' "$port" "$port" >> "$tmp"
    fi

    # User (run_as field → Docker user directive)
    local run_as=$(yq -r "${s}.run_as // \"\"" "$cfg")
    if [[ -n "$run_as" ]]; then
        echo "    user: \"${run_as}\"" >> "$tmp"
    fi

    # Environment (TZ always included)
    echo "    environment:" >> "$tmp"
    echo "      TZ: \"${tz}\"" >> "$tmp"
    _cg_write_env_vars "$s" "$cfg" "$tmp"

    # Volumes (data dir auto-mounted + user-defined)
    local data_dir="${data_base}/${svc_name}"
    echo "    volumes:" >> "$tmp"
    echo "      - ${data_dir}:/data:rw" >> "$tmp"
    _cg_write_user_volumes "$s" "$data_dir" "$cfg" "$tmp"

    # Healthcheck
    _cg_write_healthcheck "$s" "$port" "$cfg" "$tmp"

    # depends_on
    local deps; deps=$(yq -r "${s}.depends_on | length" "$cfg")
    if [[ "$deps" -gt 0 ]]; then
        echo "    depends_on:" >> "$tmp"
        while IFS= read -r dep; do
            printf '      %s:\n        condition: service_healthy\n' "$dep" >> "$tmp"
        done < <(yq -r "${s}.depends_on[]" "$cfg")
    fi

    # Resource limits + network
    _cg_write_deploy_and_net "$cpu" "$mem" "$tmp"

    # Extra containers
    local ec_count; ec_count=$(yq -r "${s}.extra_containers | length" "$cfg")
    for ((i = 0; i < ec_count; i++)); do
        _cg_write_extra_container "${s}.extra_containers[${i}]" "$cfg" "$tz" "$tmp"
    done

    # Networks section
    printf '\nnetworks:\n  %s:\n    external: true\n' "$_CG_NET" >> "$tmp"

    # Validate or dry-run
    if [[ "$dry_run" == "true" ]]; then
        print_info "[dry-run] Would generate compose file for ${svc_name}:"
        cat "$tmp"; return 0
    fi
    if docker compose -f "$tmp" config --quiet 2>/dev/null; then
        mkdir -p "${out_dir}/${svc_name}"
        cp "$tmp" "${out_dir}/${svc_name}/docker-compose.yml"
        print_success "Generated compose file: ${out_dir}/${svc_name}/docker-compose.yml"
    else
        print_error "Generated compose file failed validation for ${svc_name}"
        cat "$tmp" >&2; return 1
    fi
}

# Write user-defined environment variables (skips TZ since it's already added)
_cg_write_env_vars() {
    local s="$1" cfg="$2" tmp="$3"
    local count; count=$(yq -r "${s}.environment | length" "$cfg")
    [[ "$count" -eq 0 ]] && return 0
    while IFS= read -r key; do
        local val; val=$(yq -r "${s}.environment.${key}" "$cfg")
        echo "      ${key}: \"${val}\"" >> "$tmp"
    done < <(yq -r "${s}.environment | keys | .[]" "$cfg")
}

# Write user-defined volumes (skip duplicates of auto-mounted data dir)
_cg_write_user_volumes() {
    local s="$1" data_dir="$2" cfg="$3" tmp="$4"
    local count; count=$(yq -r "${s}.volumes | length" "$cfg")
    [[ "$count" -eq 0 ]] && return 0
    while IFS= read -r vol; do
        [[ "$vol" != "${data_dir}:/data:rw" ]] && echo "      - ${vol}" >> "$tmp"
    done < <(yq -r "${s}.volumes[]" "$cfg")
}

# Write healthcheck (custom from definition or default HTTP check on port)
_cg_write_healthcheck() {
    local s="$1" port="$2" cfg="$3" tmp="$4"
    local hc; hc=$(yq -r "${s}.healthcheck // \"\"" "$cfg")
    if [[ -n "$hc" ]] && [[ "$hc" != "null" ]]; then
        echo "    healthcheck:" >> "$tmp"
        local test_json; test_json=$(yq -r "${s}.healthcheck.test | @json" "$cfg" 2>/dev/null || echo "")
        [[ -n "$test_json" ]] && [[ "$test_json" != "null" ]] && echo "      test: ${test_json}" >> "$tmp"
        local int tmo ret
        int=$(yq -r "${s}.healthcheck.interval // \"${_CG_HC_INT}\"" "$cfg")
        tmo=$(yq -r "${s}.healthcheck.timeout // \"${_CG_HC_TMO}\"" "$cfg")
        ret=$(yq -r "${s}.healthcheck.retries // ${_CG_HC_RET}" "$cfg")
        printf '      interval: %s\n      timeout: %s\n      retries: %s\n' "$int" "$tmo" "$ret" >> "$tmp"
    elif [[ -n "$port" ]]; then
        cat >> "$tmp" << EOF
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${port}/"]
      interval: ${_CG_HC_INT}
      timeout: ${_CG_HC_TMO}
      retries: ${_CG_HC_RET}
EOF
    fi
}

# Write deploy.resources.limits + networks for a service block
_cg_write_deploy_and_net() {
    local cpu="$1" mem="$2" tmp="$3"
    cat >> "$tmp" << EOF
    deploy:
      resources:
        limits:
          cpus: "${cpu}"
          memory: ${mem}
    networks:
      - ${_CG_NET}
EOF
}

# Write a single extra_container block
_cg_write_extra_container() {
    local ec="$1" cfg="$2" tz="$3" tmp="$4"
    local name; name=$(yq -r "${ec}.name" "$cfg")
    local img; img=$(yq -r "${ec}.image" "$cfg")

    printf '\n  %s:\n    container_name: %s\n    restart: unless-stopped\n    image: %s\n' \
        "$name" "$name" "$img" >> "$tmp"

    # Environment
    echo "    environment:" >> "$tmp"
    echo "      TZ: \"${tz}\"" >> "$tmp"
    _cg_write_env_vars "$ec" "$cfg" "$tmp"

    # Volumes
    local vc; vc=$(yq -r "${ec}.volumes | length" "$cfg")
    if [[ "$vc" -gt 0 ]]; then
        echo "    volumes:" >> "$tmp"
        while IFS= read -r vol; do echo "      - ${vol}" >> "$tmp"; done < <(yq -r "${ec}.volumes[]" "$cfg")
    fi

    # Healthcheck
    local hc; hc=$(yq -r "${ec}.healthcheck // \"\"" "$cfg")
    if [[ -n "$hc" ]] && [[ "$hc" != "null" ]]; then
        echo "    healthcheck:" >> "$tmp"
        local tj; tj=$(yq -r "${ec}.healthcheck.test | @json" "$cfg" 2>/dev/null || echo "")
        [[ -n "$tj" ]] && [[ "$tj" != "null" ]] && echo "      test: ${tj}" >> "$tmp"
        local int tmo ret
        int=$(yq -r "${ec}.healthcheck.interval // \"${_CG_HC_INT}\"" "$cfg")
        tmo=$(yq -r "${ec}.healthcheck.timeout // \"${_CG_HC_TMO}\"" "$cfg")
        ret=$(yq -r "${ec}.healthcheck.retries // ${_CG_HC_RET}" "$cfg")
        printf '      interval: %s\n      timeout: %s\n      retries: %s\n' "$int" "$tmo" "$ret" >> "$tmp"
    fi

    # Resource limits + network (defaults for sidecars)
    _cg_write_deploy_and_net "$_CG_CPU" "$_CG_MEM" "$tmp"
}
