#!/bin/bash
set -euo pipefail

# Duplicate Scan Module — Photo Archive Audit
# Purpose: Estimate duplicate files in a photo archive using jdupes content hashing
# Location: scripts/operations/utils/immich/duplicate_scan.sh
# Requirements: 48.1-48.5, 51.3, 53.3, 53.5, 53.6
#
# Usage: duplicate_scan.sh <archive_directory> [--report]
#   archive_directory  Path to the photo archive (read-only access)
#   --report           Generate detailed duplicate report file in current directory
#
# Safety: All operations are READ-ONLY. No files in the archive are modified or deleted.
#         jdupes runs in summary/estimate-only mode — never in delete mode.
# Dependencies: jdupes (optional — if missing, prints warning and exits 0)
#
# Output patterns consumed by orchestrator (photo_audit.sh):
#   "Duplicate file groups: NNN"
#   "Estimated wasted space: XXX"

# ─── Configuration ───────────────────────────────────────────────────────────

ARCHIVE_DIR="${1:?Usage: duplicate_scan.sh <archive_directory> [--report]}"
REPORT_FLAG="${2:-}"

# ─── Validation ──────────────────────────────────────────────────────────────

if [[ ! -d "$ARCHIVE_DIR" ]]; then
    echo "ERROR: Archive directory '$ARCHIVE_DIR' does not exist" >&2
    exit 1
fi

if [[ ! -r "$ARCHIVE_DIR" ]]; then
    echo "ERROR: Archive directory '$ARCHIVE_DIR' is not readable" >&2
    exit 1
fi

# ─── Dependency Check (jdupes is OPTIONAL) ───────────────────────────────────
# Req 48.4: If jdupes not installed, display warning and skip gracefully

echo "--- Duplicate Detection ---"

if ! command -v jdupes &>/dev/null; then
    echo "WARNING: jdupes is not installed — skipping duplicate detection" >&2
    echo "  Install with: sudo apt install jdupes" >&2
    echo ""
    echo "Duplicate file groups: 0"
    echo "Estimated wasted space: N/A (jdupes not installed)"
    echo ""
    echo "--- Duplicate Detection Complete ---"
    exit 0
fi

# ─── Duplicate Scan (read-only, estimate-only) ──────────────────────────────
# Req 48.1: Use jdupes with content hashing to identify duplicate file groups
# Req 48.3: Operate in estimate-only mode (no deletion, no modification)
# Flags:
#   -r  Recursive scan
#   -m  Summarize duplicate matches (print summary)

# Run jdupes in summary mode to get duplicate group count and wasted space
# The -m flag prints a summary line with bytes wasted
# Req 48.2: Report total number of duplicate file groups and total wasted space
JDUPES_SUMMARY=$(jdupes -r -m "$ARCHIVE_DIR" 2>/dev/null || true)

# Extract duplicate set count from summary output
# jdupes -m outputs lines like: "X duplicate files (in Y groups), occupying Z bytes"
DUP_GROUPS=0
WASTED_SPACE="0 bytes"

if [[ -n "$JDUPES_SUMMARY" ]]; then
    # Count duplicate groups from the summary
    # jdupes -m prints a summary line at the end with group count
    GROUPS_LINE=$(echo "$JDUPES_SUMMARY" | grep -i "duplicate" | tail -1 || true)

    if [[ -n "$GROUPS_LINE" ]]; then
        # Extract group count: "N duplicate files (in M groups)"
        DUP_GROUPS=$(echo "$GROUPS_LINE" | grep -oP '\(\s*in\s+\K\d+' || echo "0")
        if [[ -z "$DUP_GROUPS" ]]; then
            DUP_GROUPS=0
        fi

        # Extract wasted space from the summary line
        WASTED_SPACE=$(echo "$GROUPS_LINE" | grep -oP 'occupying\s+\K.*' || echo "unknown")
        if [[ -z "$WASTED_SPACE" ]]; then
            WASTED_SPACE="unknown"
        fi
    fi
fi

echo "Duplicate file groups: $DUP_GROUPS"
echo "Estimated wasted space: $WASTED_SPACE"

# ─── Optional Detailed Report ────────────────────────────────────────────────
# Req 48.5: Report results to console and optionally to a detailed report file
# Req 51.3: Generate duplicate detection report file when --report flag provided

if [[ "$REPORT_FLAG" == "--report" ]]; then
    echo ""
    echo "--- Generating Duplicate Report ---"

    REPORT_FILE="./duplicate_report.txt"

    # Write header
    {
        echo "# Duplicate File Report"
        echo "# Archive: $ARCHIVE_DIR"
        echo "# Date: $(date)"
        echo "# Generated by: duplicate_scan.sh"
        echo "#"
        echo "# Groups of identical files are separated by blank lines."
        echo "# Files within each group have identical content (byte-for-byte match)."
        echo ""
    } > "$REPORT_FILE"

    # Run jdupes in listing mode (outputs groups of duplicate files)
    # Each group is separated by a blank line
    jdupes -r "$ARCHIVE_DIR" >> "$REPORT_FILE" 2>/dev/null || true

    REPORT_LINES=$(wc -l < "$REPORT_FILE")
    echo "Duplicate report written to: $REPORT_FILE ($REPORT_LINES lines)"
fi

echo ""
echo "--- Duplicate Detection Complete ---"
